version: '3'

services:
  blog:
    image: ambrest/vue-blog
    container_name: ambrest-blog
    command: "http://192.168.99.100:4000/api"
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
