version: '3'

services:
  blog:
    image: vue-blog
    container_name: ambrest-blog
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
